#spring.datasource.url=jdbc:mysql://localhost:3306/practice
#spring.datasource.username=root
#spring.datasource.password=*****
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/prajanetraDB?sslMode=VERIFY_IDENTITY
spring.datasource.username=2rDgWcTrR2b3UyY.root
spring.datasource.password=WrwOSMwx1zJMaW2c
jwt.secret=securejwtsecretforprajanetra0198

spring.security.oauth2.client.registration.google.client-id=636805099378-23ccro3iles7oa30lsti53fe7l81fpk2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#supabase.url=https://ifdjmerzalmgbipzoexh.supabase.co
#supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZGptZXJ6YWxtZ2JpcHpvZXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5Njc4MDAsImV4cCI6MjA3OTU0MzgwMH0.JbzQpA3NOeMfF6njixPm7UCIy8Rr9rn-XuUN6xa4TJU
#supabase.bucket=complaint-images

supabase.url=https://hhotfsilesrrcomokwke.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhob3Rmc2lsZXNycmNvbW9rd2tlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTAwODA3OCwiZXhwIjoyMDg0NTg0MDc4fQ.gR47l07biyfl9CYYRmN5NzzJODkr7Fywm38qD_c9U08
supabase.bucket=ComplaintImages

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

